name: egk
favicon: null
layout_spectrum: 0.25081
typography_spectrum: 0.78092
title: Edmond Gabriel Kalandadze
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#3e3e3e'
    - '#8c8c8c'
    - '#a9a9a9'
    - '#d1d1d1'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
